### ISSUE TITLE
gh-pages branch should be a different repo.

### ISSUE THREAD

**Issue by devloop0** [poi-the-machine/the-machine#12]
Most other github repositories leave their github.io websites in a different repo. I feel that anything not directly related to the machine development should be in a different repository. If it's okay with everyone, I can move it to a different repository.

**Comment by kodbilenadam** [comment]
Move it.

**Comment by devloop0** [comment]
Okay, I moved it to a new repo, but you are going to have to recreate the website; the old link doesn't work. Copy and paste? (I'm going to close this issue now).
