### ISSUE TITLE
Rename testing branch to Day 0

### ISSUE THREAD

**Issue by devloop0** [poi-the-machine/the-machine#13]
Since our next milestone is day zero, and everything in the testing branch is geared towards the day zero software, I'm wondering whether or not we should change the name of the testing branch to day-zero. I'm simply asking because the desktop application is nearing completion of that milestone and I would like to start working on heavy UI improvements towards day one (another branch). Suggestions are welcome...

**Comment by devloop0** [comment]
I haven't heard any discussion on this topic so I am going to assume that everyone is okay with it. I am going to wait one more day before moving it unless anyone has any opposition to this.

**Comment by Xalaxis** [comment]
I think we should leave it as testing.  Otherwise we will have lots of
branches which are all varying amounts of out-of-date.  We can use github
builds for versioning IMO.

**Comment by devloop0** [comment]
Okay, I'll leave it as is and close this issue.
