### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by Magelfik** [poi-the-machine/the-machine#16]
Hi there,

I just wanted to let you know that the x64 link seems to be down. 

Was it intentional ?

Thanks in advance.

**Comment by devloop0** [comment]
Thanks, I removed the old binaries and there are new ones. I will update them accordingly.

**Comment by devloop0** [comment]
Sorry for the delay, I updated the binaries on the README.md page. I'm closing this issue. Thanks for the interest!
