### ISSUE TITLE
No one working on it!

### ISSUE THREAD

**Issue by NGTmeaty** [poi-the-machine/the-machine#3]

**Comment by devloop0** [comment]
Hi, thanks for the feedback. I'm glad people in the community are interested in our project. Don't worry, we haven't forgotten about it. Currently, were working on a windows version of the app as well. Hopefully, our first code commit will come in soon!

**Comment by Xalaxis** [comment]
You could have added a brief description @NGTmeaty , but rest assured, we are working on it :smile:.

First build should be up sometime in the next week at least I expect.

**Comment by NGTmeaty** [comment]
By accidently hit add before adding a description! Whoops!

**Comment by NGTmeaty** [comment]
What will the windows version run off? Will it just connect to a site?

**Comment by devloop0** [comment]
I'm working on the windows version. It is a native app. I'm planning to keep it in a zip file, and you can extract and run it as an executable.

**Comment by NGTmeaty** [comment]
My question remains the same, will it either a, use html/website or run on c or c#

**Comment by devloop0** [comment]
Sorry, I didn't understand your question. Native apps on windows are usually written in C# or C++ (unless they are web apps). This one is written in C#.

**Comment by Xalaxis** [comment]
@NGTmeaty , what @devloop0 is saying is essentially it's definitely not a web-app and is natively coded.  We are still discussing how they should/should not link into a back-end.

**Comment by NGTmeaty** [comment]
got it.

**Comment by kodbilenadam** [comment]
@NGTmeaty Also there will be a web and mobile clients as well :+1:
