### ISSUE TITLE
Facial detection and recognition

### ISSUE THREAD

**Issue by devloop0** [poi-the-machine/the-machine#4]
Facial detection is almost done and will be coming in the first commit for the windows app.

**Comment by DeviantInterface** [comment]
AWESOME!

On Thursday, June 18, 2015, devloop0 <notifications@github.com> wrote:

> Facial detection is almost done and will be coming in the first commit for
> the windows app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/poi-the-machine/the-machine/issues/4>.
>


-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by Xalaxis** [comment]
I quite agree @DeviantInterface ... I quite agree.

Good job @devloop0

**Comment by devloop0** [comment]
Quick status update on this: the facial detection part of this is undergoing internal testing and will soon be out. Facial recognition support has already been begun and will be in the commit after this one.

**Comment by DeviantInterface** [comment]
Will there be a mobile compatible version?

On Sunday, June 21, 2015, devloop0 <notifications@github.com> wrote:

> Quick status update on this: the facial detection part of this is
> undergoing internal testing and will soon be out. Facial recognition
> support has already been begun and will be in the commit after this one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/poi-the-machine/the-machine/issues/4#issuecomment-113878792>
> .
>


-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by Xalaxis** [comment]
At this time I don't think we have the expertise to make that a reality.
We don't really have any Android or IPhone developers in the project at
this time.

**Comment by devloop0** [comment]
Let me add to this by saying that it is definitely a long-term goal but will not be done in the foreseeable future, at least until the mobile and web versions are highly stable.

**Comment by devloop0** [comment]
Sorry, I meant the web and desktop versions, my bad.

**Comment by Xalaxis** [comment]
I would say that basic facial detection is done at this stage.  Perhaps close this Issue and open a new one with specific goals for Day 1?

**Comment by devloop0** [comment]
I'm going to leave this open until the facial recognition features as done as well. Once that is done, then I will close this issue and create a new milestone for UI enhancements for Day 1.

**Comment by devloop0** [comment]
I am proud to say that with the help of all of the other developers in this project, we have officially completed support for facial detection and recognition on the windows client for the day zero goal. (The download link is in the testing repository). Of course, this does not mean that there are no bugs and any issues regarding the implementation are welcome, but if everyone is okay with this, I will go ahead and close this issue and create a new milestone for day 1.

**Comment by Xalaxis** [comment]
Go ahead.  (As long as you also think build one is not yet finished, just
this aim is) (sorry, that's probably worded confusingly)
