### ISSUE TITLE
Target UI for the Desktop Application

### ISSUE THREAD

**Issue by devloop0** [poi-the-machine/the-machine#5]
Screenshots of both Samaritan and the Machine's UI when they are looking at people as well as when Samaritan takes input from people would be helpful.

**Comment by Xalaxis** [comment]
Note: You can't assign more than one person apparently :wink:

**Comment by Xalaxis** [comment]
Deviant, can you handle this?

**Comment by Xalaxis** [comment]
@devloop0 Did @DeviantInterface do this through Skype?

**Comment by devloop0** [comment]
Preferably, I would like some mockups and gifs posted in a folder, but this issue seems somewhat superfluous, I'm going to go ahead and close this if it is okay with you @Xalaxis.

**Comment by Xalaxis** [comment]
I think we should leave it open until we get a reply from @DeviantInterface , (As he has gone AWOL on both Skype and Github, he might have prepared something already).

**Comment by devloop0** [comment]
Sounds fine with me.

**Comment by devloop0** [comment]
@DeviantInterface, all those mockups that you were working on in Skype would be excellent in  'mockups' folder in the repo. Could you commit them?

**Comment by DeviantInterface** [comment]
I'll need help, but sure

On Monday, June 29, 2015, devloop0 <notifications@github.com> wrote:

> @DeviantInterface <https://github.com/DeviantInterface>, all those
> mockups that you were working on in Skype would be excellent in 'mockups'
> folder in the repo. Could you commit them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/poi-the-machine/the-machine/issues/5#issuecomment-116871935>
> .
>


-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by DeviantInterface** [comment]
What's with the spastic assigning and unassigning me guys XD

**Comment by Xalaxis** [comment]
It was me getting used to assigning people @DeviantInterface .  Did we sort this yet?

**Comment by DeviantInterface** [comment]
Sort what?

On Monday, July 6, 2015, Matthew Wolffsohn <notifications@github.com> wrote:

> It was me getting used to assigning people @DeviantInterface
> <https://github.com/DeviantInterface> . Did we sort this yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/poi-the-machine/the-machine/issues/5#issuecomment-118839695>
> .
>


-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System

**Comment by Xalaxis** [comment]
Deviant's Mockups.  Did they get put in any of the repo branches?

**Comment by DeviantInterface** [comment]
Consider it sorted

On Monday, July 6, 2015, Deviant Interface <
halokid687doesminecraft@gmail.com> wrote:

> Sort what?
>
> On Monday, July 6, 2015, Matthew Wolffsohn <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> It was me getting used to assigning people @DeviantInterface
>> <https://github.com/DeviantInterface> . Did we sort this yet?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/poi-the-machine/the-machine/issues/5#issuecomment-118839695>
>> .
>>
>
>
> --
> ///Deviant
> Name: Mccree, Daniel P.
> SSN: XXX-XX-2840
> Designation: Threat To System
>
>

-- 
///Deviant
Name: Mccree, Daniel P.
SSN: XXX-XX-2840
Designation: Threat To System
