### ISSUE TITLE
Day counter

### ISSUE THREAD

**Issue by Xalaxis** [poi-the-machine/the-machine#6]
A script which updates a json file with the current number of days the system has been running.  I should have this done by sometime later today hopefully.

**Comment by Xalaxis** [comment]
Current progress:
![](https://puu.sh/iuH1V.png)

**Comment by devloop0** [comment]
If you need help with this, let me know @Xalaxis.

**Comment by Xalaxis** [comment]
@devloop0 has committed a fix for the syntax errors.  I just need to test this on a live server and it should be ready to merge to main.

**Comment by Xalaxis** [comment]
Code finished and pull request submitted.  Has been fully tested by me, but I'll leave the pull request up so that someone can peer review, @devloop0 ?

Values returned are:
* runseconds - The number of seconds run, integer
* runminutes - The number of minutes run, integer
* runhours - The number of hours run, integer
* rundays - The number of days run, integer
* serveroverload - Whether the program should back off from the server for a period of time (hour?) as the server is overloaded, boolean
* devstatus - Whether the program is in a 'beta', 'alpha' or otherwise development stage (So it would know if it's a final release), boolean
* latestver - The latest build of the program (for future updating purposes), string

**Comment by Xalaxis** [comment]
Reopening issue until peer reviewed.
